src/main/java/io/supertokens/storage/mysql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/mysql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/mysql/utils/RowMapper.java
**What does this PR do?**
*   This PR adds RowMapper for creating object from resultset.
=> Add RowMapper for separting logic for creating corresponding object from resultset

src/main/java/io/supertokens/storage/mysql/Start.java
Fix fallthrough while choosing the isolation level
This was caught by CI/CD, no new tests were necessary
Internal change
=> fix: isolation level fallthrough

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/UserMetadataQueries.java, src/test/java/io/supertokens/storage/mysql/test/DeadlockTest.java
Adds user metadata support
- supertokens/supertokens-core#381 
- supertokens/supertokens-core#239 
Tests were added in the core PR
supertokens/docs#241
=> feat: implement usermetadata methods

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/UserRoleQueries.java
Adds UserRoles support 
- https://github.com/supertokens/supertokens-core/pull/414
Run core tests
- none
- none
=> feat: adds user role support

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/SessionQueries.java
=> feat: returns only non expired session handles for user

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/UserIdMappingQueries.java
Adds usesrIdMapping support
- https://github.com/supertokens/supertokens-core/issues/463
- runs core tests
=> feat: adds userIdMapping queries

src/main/java/io/supertokens/storage/mysql/queries/UserIdMappingQueries.java
=> fixes getUserIdMappingWithUserIds query

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/ConnectionPool.java, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/Config.java, src/main/java/io/supertokens/storage/mysql/output/Logging.java, src/test/java/io/supertokens/storage/mysql/test/LogLevelTest.java, src/test/java/io/supertokens/storage/mysql/test/LoggingTest.java
Implments log level
- https://github.com/supertokens/supertokens-core/issues/494
Checking logger is not logging when different log levels are enabled
=> feat: implements log level

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json
- https://github.com/supertokens/supertokens-core/issues/525
=> updates dependencies

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/main/java/io/supertokens/storage/mysql/queries/DashboardQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java
=> feat: Dashboard APIs

CHANGELOG.md, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/main/java/io/supertokens/storage/mysql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java
feat: Storage layer to monitor active users
- https://github.com/supertokens/supertokens-core/pull/585
- x ] Had installed and ran the pre-commit hook
=> feat: Storage layer to monitor active users

src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/ActiveUsersQueries.java
feat: Implement queries required for TOTP usage stats
- https://github.com/supertokens/supertokens-mysql-plugin/pull/44
=> feat: Implement queries required for TOTP usage stats

CHANGELOG.md, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/main/java/io/supertokens/storage/mysql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/TOTPQueries.java, src/test/java/io/supertokens/storage/mysql/test/DeadlockTest.java, src/test/java/io/supertokens/storage/mysql/test/StorageLayerTest.java
Implement TOTP recipe features with MySQL plugin.
- https://github.com/supertokens/supertokens-core/issues/554
- https://github.com/supertokens/supertokens-core/pull/564
Same tests as Inmemorydb implementation along with a few more added in `StorageLayerTest.java`
=> feat: Add support for TOTP recipe

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java
=> feat: adds dashboard search support

src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java
=> fix: bug in dashboard search query

src/main/java/io/supertokens/storage/mysql/queries/SessionQueries.java
=> fix: add missing use_static_key column to table creation query

src/test/java/io/supertokens/storage/mysql/test/InMemoryDBTest.java
=> test: fix exception list in test definition

src/main/java/io/supertokens/storage/mysql/Start.java
=> fix: increase transaction retry count&timeout

CHANGELOG.md
=> chore: clarify migration steps in changelog

.circleci/config.yml, CHANGELOG.md, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/MultitenancyQueries.java, src/main/java/io/supertokens/storage/mysql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/mysql/queries/multitenancy/TenantConfigSQLHelper.java, src/main/java/io/supertokens/storage/mysql/queries/multitenancy/ThirdPartyProviderClientSQLHelper.java, src/main/java/io/supertokens/storage/mysql/queries/multitenancy/ThirdPartyProviderSQLHelper.java
=> fix: Test fixes

src/main/java/io/supertokens/storage/mysql/Start.java, src/test/java/io/supertokens/storage/mysql/test/DeadlockTest.java
=> fix: exponential backoff in transaction retry

src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java
=> fix: get tables impl

src/main/java/io/supertokens/storage/mysql/ConnectionPool.java, src/main/java/io/supertokens/storage/mysql/ResourceDistributor.java, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/test/java/io/supertokens/storage/mysql/test/ConfigTest.java, src/test/java/io/supertokens/storage/mysql/test/InMemoryDBTest.java, src/test/java/io/supertokens/storage/mysql/test/LoggingTest.java, src/test/java/io/supertokens/storage/mysql/test/TableCreationTest.java, src/test/java/io/supertokens/storage/mysql/test/TestingProcessManager.java, src/test/java/io/supertokens/storage/mysql/test/multitenancy/StorageLayerTest.java
=> fix: config normalisation

src/main/java/io/supertokens/storage/mysql/Start.java
=> fix: close hikari appender for base tenant

src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/output/Logging.java, src/test/java/io/supertokens/storage/mysql/test/LoggingTest.java
=> fix: hikari logging test

src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/test/java/io/supertokens/storage/mysql/test/multitenancy/StorageLayerTest.java
=> fix: updated conflict validation test

src/main/java/io/supertokens/storage/mysql/ConnectionPool.java, src/main/java/io/supertokens/storage/mysql/Start.java, src/test/java/io/supertokens/storage/mysql/test/TestMainThread.java, src/test/java/io/supertokens/storage/mysql/test/httpRequest/HttpRequestForTesting.java, src/test/java/io/supertokens/storage/mysql/test/httpRequest/HttpRequestMocking.java, src/test/java/io/supertokens/storage/mysql/test/httpRequest/HttpResponseException.java
=> fix: main thread and test

src/main/java/io/supertokens/storage/mysql/output/Logging.java
=> fix: logging fix

src/main/java/io/supertokens/storage/mysql/Start.java
=> fix: main thread fix

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/mysql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/mysql/queries/ThirdPartyQueries.java
- https://github.com/supertokens/supertokens-node/pull/471
=> fix: app id in user id queries

src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/PasswordlessQueries.java, src/test/java/io/supertokens/storage/mysql/test/DeadlockTest.java, src/test/java/io/supertokens/storage/mysql/test/Utils.java
=> fix: deadlock test

src/main/java/io/supertokens/storage/mysql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/mysql/queries/ThirdPartyQueries.java
=> fix: misc fixes

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/mysql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/mysql/queries/UserIdMappingQueries.java
- https://github.com/supertokens/supertokens-core/issues/872
=> fix: email verified in login methods

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/Config.java, src/main/java/io/supertokens/storage/mysql/utils/ConfigMapper.java
=> fix: config type validation

src/main/java/io/supertokens/storage/mysql/utils/ConfigMapper.java
=> fix: null handling in config mapper

src/test/java/io/supertokens/storage/mysql/test/DbConnectionPoolTest.java
=> fix: cicd tests

src/test/java/io/supertokens/storage/mysql/test/DbConnectionPoolTest.java
=> fix: flaky test

CHANGELOG.md, config.yaml, devConfig.yaml, src/main/java/io/supertokens/storage/mysql/ConnectionPool.java, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/test/java/io/supertokens/storage/mysql/test/DbConnectionPoolTest.java, src/test/java/io/supertokens/storage/mysql/test/SuperTokensSaaSSecretTest.java
=> fix: adds idle timeout and minimum idle configs

CHANGELOG.md, build.gradle, config.yaml, devConfig.yaml, src/main/java/io/supertokens/storage/mysql/ConnectionPool.java, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/config/MySQLConfig.java, src/test/java/io/supertokens/storage/mysql/test/DbConnectionPoolTest.java, src/test/java/io/supertokens/storage/mysql/test/SuperTokensSaaSSecretTest.java
=> fix: connection pool test and idle configs

CHANGELOG.md, build.gradle
- https://github.com/supertokens/supertokens-core/issues/926
=> fix: Vulnerability fix

build.gradle, implementationDependencies.json
=> fix: dependencies

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/UserRolesQueries.java, src/test/java/io/supertokens/storage/mysql/test/DbConnectionPoolTest.java, src/test/java/io/supertokens/storage/mysql/test/multitenancy/StorageLayerTest.java, src/test/java/io/supertokens/storage/mysql/test/multitenancy/TestUserPoolIdChangeBehaviour.java
- Implements `deleteAllUserRoleAssociationsForRole`
- Drops `(app_id, role)` foreign key constraint on `user_roles` table
- https://github.com/supertokens/supertokens-core/issues/941
- If no such branch exists, then create one from the latest …
=> fix: fixes storage handling for non-auth recipes

.circleci/config.yml
=> fix: cicd config

src/test/java/io/supertokens/storage/mysql/test/OneMillionUsersTest.java
=> fix: one million user test

src/test/java/io/supertokens/storage/mysql/test/OneMillionUsersTest.java
=> fix: one million user test fix

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/mysql/queries/UserIdMappingQueries.java
=> fix: backports for core 8.0

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/EmailVerificationQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/SessionQueries.java, src/main/java/io/supertokens/storage/mysql/queries/UserIdMappingQueries.java
=> fix: backports to core 7.0

CHANGELOG.md, build.gradle, implementationDependencies.json, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java
=> fix: backports to core 5.0

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json, src/main/java/io/supertokens/storage/mysql/ConnectionPool.java, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/MultitenancyQueries.java, src/test/java/io/supertokens/storage/mysql/test/Utils.java, src/test/java/io/supertokens/storage/mysql/test/multitenancy/TestForNoCrashDuringStartup.java
=> fix: backport 8.0.3

CHANGELOG.md
=> fix: mysql migration for multitenancy

src/test/java/io/supertokens/storage/mysql/test/multitenancy/StorageLayerTest.java
=> fix: build

.circleci/doOneMillionUsersTests.sh, .circleci/doTests.sh
=> fix: gradle.properties in tests

CHANGELOG.md, build.gradle, src/test/java/io/supertokens/storage/mysql/test/multitenancy/TestForNoCrashDuringStartup.java
=> fix: tests

src/test/java/io/supertokens/storage/mysql/test/multitenancy/TestForNoCrashDuringStartup.java
=> fix: cicd test

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/ActiveUsersQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/test/java/io/supertokens/storage/mysql/test/OneMillionUsersTest.java
Adds index for MAU
- https://github.com/supertokens/supertokens-core/issues/994
=> fix: index for MAU

src/test/java/io/supertokens/storage/mysql/test/OneMillionUsersTest.java, src/test/java/io/supertokens/storage/mysql/test/Utils.java
=> fix: Test fix

CHANGELOG.md, src/main/java/io/supertokens/storage/mysql/queries/OAuthQueries.java
=> fix: index creation query

src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/OAuthQueries.java
Simplifying jti handling it database
=> fix: jti listing

.circleci/config.yml
=> ci: add missing image to ci config

src/main/java/io/supertokens/storage/mysql/queries/BulkImportQueries.java
=> Fix: bulk import syntax

src/main/java/io/supertokens/storage/mysql/Start.java
=> fix: fixing test via proper exception handling

src/main/java/io/supertokens/storage/mysql/BulkImportProxyStorage.java, src/main/java/io/supertokens/storage/mysql/queries/BulkImportQueries.java
=> feat!: drop mysql57 support bulk import

src/main/java/io/supertokens/storage/mysql/queries/SessionQueries.java
=> fix: session queries

CHANGELOG.md, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/SessionQueries.java
The lack of index on session_info's (app_id, user_id) was causing performance issues at one of the users, so here it goes.
- If no such branch exists, then create one …
=> fix: add index for session_info on user_id, app_id

CHANGELOG.md, build.gradle, pluginInterfaceSupported.json
=> fix: version update

.circleci/doTests.sh
=> ci: fix ci test script

.circleci/doOneMillionUsersTests.sh, .circleci/doTests.sh, .github/workflows/tests.yml
=> ci: fix rewriteBatchedStatements in ci config

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/mysql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/mysql/queries/ThirdPartyQueries.java
=> fix: slow queries for account linking

CHANGELOG.md, build.gradle, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java
=> fix: user search

CHANGELOG.md, src/main/java/io/supertokens/storage/mysql/output/CustomLayout.java, src/main/java/io/supertokens/storage/mysql/output/Logging.java
=> fix: structured logging

CHANGELOG.md, src/main/java/io/supertokens/storage/mysql/Start.java
=> fix: webauthn review fixes

pluginInterfaceSupported.json
=> fix: plugin supported version

src/main/java/io/supertokens/storage/mysql/Start.java, src/main/java/io/supertokens/storage/mysql/queries/EmailPasswordQueries.java, src/main/java/io/supertokens/storage/mysql/queries/GeneralQueries.java, src/main/java/io/supertokens/storage/mysql/queries/PasswordlessQueries.java, src/main/java/io/supertokens/storage/mysql/queries/ThirdPartyQueries.java, src/main/java/io/supertokens/storage/mysql/queries/WebAuthNQueries.java
=> fix: bulk migration account linking test fixes
